// =========================
// MAPS.JS
// Random 10x20 map pool
// v0.5.6 map pool: 150 tree-style layouts
// =========================
//
// Legend:
// # = blocked / no room
// E = entrance
// R = regular room
// M = monster room
// C = normal chest room
// L = locked rare chest room
// B = boss room
// S = shrine / end room
// N = NPC / shop / safe room
//
// Rules enforced:
// - 150 maps total.
// - 50 short/simple, 75 medium-to-long, 25 long/complex.
// - Shrine fixed at H18.
// - Boss appears on 75 of 150 maps and, when present, is fixed at H17.
// - No trap rooms.
// - Entrance has exactly one connected room, directly below E.
// - Chests and NPC rooms only appear on dead ends.
// - Maps are connected trees: branches may split but never reconnect into loops.
// - Map selection remains fully random in index.html.
// =========================

const MAPS = {
  random_001: {
    id: "random_001",
    name: "Random Dungeon 001",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#####E####",
      "#####R####",
      "#####R####",
      "#####R##L#",
      "#####R##R#",
      "####CRRRR#",
      "########R#",
      "########R#",
      "########RC",
      "#######RR#",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_002: {
    id: "random_002",
    name: "Random Dungeon 002",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "######E###",
      "######R###",
      "######R###",
      "#####MR###",
      "######RRC#",
      "######R###",
      "######R###",
      "######R###",
      "######R###",
      "#####CR###",
      "######MRM#",
      "######R###",
      "######R###",
      "######RR##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_003: {
    id: "random_003",
    name: "Random Dungeon 003",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "#####E####",
      "#####R####",
      "#####R####",
      "#####R####",
      "####RR####",
      "##CRR#####",
      "####R#####",
      "##CRRRRR##",
      "#######MRM",
      "#####CMR##",
      "#######M##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_004: {
    id: "random_004",
    name: "Random Dungeon 004",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#####E####",
      "#####R####",
      "#####R####",
      "#####RN###",
      "#####R####",
      "#####RRRM#",
      "########R#",
      "#######CR#",
      "########R#",
      "########R#",
      "########RR",
      "#####LRRR#",
      "########R#",
      "#######MR#",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_005: {
    id: "random_005",
    name: "Random Dungeon 005",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "########E#",
      "########R#",
      "########R#",
      "########RR",
      "########R#",
      "########RC",
      "########R#",
      "#######RR#",
      "####MRRR##",
      "#######R##",
      "#######M##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_006: {
    id: "random_006",
    name: "Random Dungeon 006",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##E#######",
      "##R#######",
      "##R#######",
      "##RRRRMR##",
      "###M###R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "######MR##",
      "#######M##",
      "#######R##",
      "#######M##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_007: {
    id: "random_007",
    name: "Random Dungeon 007",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#####E####",
      "#####R####",
      "#####R####",
      "#RMRRR####",
      "#M########",
      "#MRC######",
      "#R########",
      "#R########",
      "#R########",
      "CR########",
      "#RRRRRRM##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_008: {
    id: "random_008",
    name: "Random Dungeon 008",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "#######E##",
      "#######R##",
      "#######R##",
      "######RR##",
      "#######R##",
      "#####RRR##",
      "#####R####",
      "##L##R####",
      "##MRRR#C##",
      "#####RRRR#",
      "########R#",
      "########R#",
      "#######RR#",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_009: {
    id: "random_009",
    name: "Random Dungeon 009",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##E#######",
      "##R#######",
      "##M#######",
      "##MRRM####",
      "#####R####",
      "#####R####",
      "#####RRRC#",
      "#####R####",
      "#####R####",
      "####CRR###",
      "######RR##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_010: {
    id: "random_010",
    name: "Random Dungeon 010",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "########E#",
      "########R#",
      "########R#",
      "######NRMC",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#####MRR##",
      "#######RM#",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######M##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_011: {
    id: "random_011",
    name: "Random Dungeon 011",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "####E#####",
      "####R#####",
      "####R#####",
      "L#RRR#####",
      "MRM#######",
      "L#M#######",
      "##R#######",
      "##R#######",
      "##RMRRRR##",
      "##R####RRM",
      "##R####R##",
      "##C##CRR##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_012: {
    id: "random_012",
    name: "Random Dungeon 012",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "####E#####",
      "####R#####",
      "####R#####",
      "####RRRM##",
      "####R#####",
      "####RRRR##",
      "#######MRC",
      "###MRRMR##",
      "###R######",
      "#MRRRRRR##",
      "####R##M##",
      "####M##R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_013: {
    id: "random_013",
    name: "Random Dungeon 013",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "########E#",
      "########R#",
      "########R#",
      "########M#",
      "########R#",
      "####RRRRR#",
      "####R#####",
      "####R#####",
      "####RC####",
      "####R#C###",
      "####RRMRR#",
      "########R#",
      "#######MM#",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_014: {
    id: "random_014",
    name: "Random Dungeon 014",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#######E##",
      "#######R##",
      "#######R##",
      "###RRRRR##",
      "###R######",
      "###R######",
      "###R######",
      "###R######",
      "###R######",
      "###R######",
      "##CR######",
      "###R######",
      "###R######",
      "###RRRRR##",
      "#####R#B##",
      "#####C#S##",
      "##########",
      "##########"
    ]
  },
  random_015: {
    id: "random_015",
    name: "Random Dungeon 015",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##E#######",
      "##RL######",
      "##R#######",
      "##R#######",
      "##RRR#####",
      "####R#####",
      "####R#####",
      "####M#####",
      "####RN####",
      "####R#####",
      "#CRRR#####",
      "####RRRM##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_016: {
    id: "random_016",
    name: "Random Dungeon 016",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##E#######",
      "##R#######",
      "##R#######",
      "##R#######",
      "#MRR######",
      "###R######",
      "###R######",
      "###R######",
      "#CRRRR####",
      "#####R####",
      "#####R####",
      "#####RRR##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_017: {
    id: "random_017",
    name: "Random Dungeon 017",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#####E####",
      "#####R####",
      "#####R####",
      "###MRR####",
      "#####RRRRC",
      "######R###",
      "#####RRR##",
      "#######R##",
      "#######M##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_018: {
    id: "random_018",
    name: "Random Dungeon 018",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#######E##",
      "#######R##",
      "#######R##",
      "####N##R##",
      "####R##M##",
      "##CRRRRR##",
      "###R######",
      "###M######",
      "###R######",
      "###RRRRR##",
      "#######R##",
      "#######R##",
      "#######M##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_019: {
    id: "random_019",
    name: "Random Dungeon 019",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "#E########",
      "#R########",
      "#R########",
      "#RRMRR####",
      "##R##R####",
      "##R##RRR##",
      "##C####R##",
      "#######RM#",
      "#####CRR##",
      "#######R##",
      "#######M##",
      "#######R##",
      "#####CRRL#",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_020: {
    id: "random_020",
    name: "Random Dungeon 020",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##E#######",
      "##R#######",
      "##R#######",
      "##MRM#####",
      "##R#######",
      "##R#######",
      "##R#######",
      "##R#######",
      "RRRR##M###",
      "###R##R###",
      "###RRRRR##",
      "#####M#M##",
      "#####C#B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_021: {
    id: "random_021",
    name: "Random Dungeon 021",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "####E#####",
      "####R#####",
      "####R#####",
      "####R#C###",
      "####RRR#M#",
      "######R#R#",
      "####CRRRR#",
      "########R#",
      "#######RRN",
      "#######R##",
      "#######M##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_022: {
    id: "random_022",
    name: "Random Dungeon 022",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "####E#####",
      "####R#####",
      "####M#####",
      "####R#####",
      "###RRRC###",
      "##MR######",
      "###R######",
      "###R######",
      "###R######",
      "##CR##C###",
      "###RRRRM##",
      "#######M##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_023: {
    id: "random_023",
    name: "Random Dungeon 023",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "####E#####",
      "####R#####",
      "###LR#####",
      "####R#####",
      "#RRRM#####",
      "#R########",
      "#R########",
      "#R########",
      "#R###C####",
      "#MRRRR####",
      "##M##RRR##",
      "##N####R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_024: {
    id: "random_024",
    name: "Random Dungeon 024",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "#E########",
      "#R########",
      "#R##C#####",
      "#R##R#####",
      "#RRRR#####",
      "##R#R#####",
      "####R#####",
      "####R#####",
      "##CMR#C###",
      "####R#M###",
      "####RRRM##",
      "#######R##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_025: {
    id: "random_025",
    name: "Random Dungeon 025",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "#####E####",
      "#####R####",
      "#####R####",
      "##CRRR####",
      "###R######",
      "###R######",
      "#NRR######",
      "###R######",
      "###R######",
      "###R######",
      "###R######",
      "#RRR######",
      "#R########",
      "#RRRMRRM##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_026: {
    id: "random_026",
    name: "Random Dungeon 026",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "####E#####",
      "####R#####",
      "####R#####",
      "####R#####",
      "####RRM###",
      "###CM#####",
      "####M#####",
      "####RMRR##",
      "#####R#RM#",
      "#####R#M##",
      "#####C#R##",
      "#######R##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_027: {
    id: "random_027",
    name: "Random Dungeon 027",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "#E########",
      "#R########",
      "#R########",
      "#R########",
      "#R########",
      "#RRRRMRR##",
      "#######R##",
      "#######R##",
      "#######R##",
      "######MRM#",
      "########R#",
      "########MC",
      "########R#",
      "#######RR#",
      "#######R##",
      "#######M##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_028: {
    id: "random_028",
    name: "Random Dungeon 028",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "###E######",
      "###R######",
      "###R######",
      "##CR######",
      "###R######",
      "##RR######",
      "##M#######",
      "##R#######",
      "##R#######",
      "##R#######",
      "##R#######",
      "##M#######",
      "##R#N#####",
      "##MRMRRR##",
      "##R##C#B##",
      "##M####S##",
      "##########",
      "##########"
    ]
  },
  random_029: {
    id: "random_029",
    name: "Random Dungeon 029",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#E########",
      "#R########",
      "#R####C###",
      "#M##M#R###",
      "CRRRRRR###",
      "######R###",
      "######R###",
      "######M###",
      "######R###",
      "######RRC#",
      "######R###",
      "######R###",
      "######R###",
      "######RR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_030: {
    id: "random_030",
    name: "Random Dungeon 030",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#######E##",
      "#######R##",
      "#######R##",
      "#####RMR##",
      "##CRRR####",
      "###L#R#C##",
      "#####R#R##",
      "#####RRM##",
      "#######MRC",
      "#######R##",
      "#######RC#",
      "#######M##",
      "#######R##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_031: {
    id: "random_031",
    name: "Random Dungeon 031",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "########E#",
      "########R#",
      "########R#",
      "########R#",
      "#RRRRRRRR#",
      "#M########",
      "#RRRR#####",
      "####M#####",
      "####R#####",
      "####R#####",
      "####R#####",
      "####M#C###",
      "####RRRR##",
      "#####C#R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_032: {
    id: "random_032",
    name: "Random Dungeon 032",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "#######E##",
      "#######R##",
      "#######R##",
      "#######R##",
      "######RMRN",
      "#####CR###",
      "######R###",
      "######R###",
      "######R###",
      "####RRR###",
      "#####R####",
      "#####R####",
      "#####RRR##",
      "#######RM#",
      "#######R##",
      "#######M##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_033: {
    id: "random_033",
    name: "Random Dungeon 033",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##E#######",
      "##R#######",
      "##R#######",
      "##R#######",
      "##RMR#####",
      "####R#####",
      "###RR#####",
      "####RR####",
      "#####R####",
      "#####R####",
      "#####MRRC#",
      "#####R#R##",
      "#####R#R##",
      "#####R#R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_034: {
    id: "random_034",
    name: "Random Dungeon 034",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##E#######",
      "##R#######",
      "##R#######",
      "#CRRRR####",
      "#####RRC##",
      "#####M####",
      "#####R####",
      "#####R####",
      "###MRR####",
      "#####R####",
      "#####R####",
      "###CRR####",
      "#####RMR##",
      "#######R##",
      "#######R##",
      "#######BL#",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_035: {
    id: "random_035",
    name: "Random Dungeon 035",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "####E#####",
      "####R#####",
      "####M#####",
      "####R#####",
      "####R#####",
      "###CMRR###",
      "######R###",
      "######RM##",
      "#######R##",
      "#######M##",
      "#######R##",
      "#######R##",
      "#######RC#",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_036: {
    id: "random_036",
    name: "Random Dungeon 036",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "###E######",
      "###R######",
      "###R######",
      "#RMR######",
      "#R########",
      "#R########",
      "#R########",
      "#R########",
      "#M########",
      "#R########",
      "#R####M###",
      "#R####R###",
      "#RRRRRRR##",
      "#R#####R##",
      "#M#####R##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_037: {
    id: "random_037",
    name: "Random Dungeon 037",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "###E######",
      "###R######",
      "###R######",
      "###R######",
      "###R######",
      "###RM#####",
      "CRMR######",
      "###RMRC###",
      "###R######",
      "###R#C####",
      "###RRRRRR#",
      "########R#",
      "#######RR#",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_038: {
    id: "random_038",
    name: "Random Dungeon 038",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##E#######",
      "##R#######",
      "##R#######",
      "##R#######",
      "##R#######",
      "##RRMR####",
      "###R#R####",
      "###M#R####",
      "#####R#C##",
      "####MR#R##",
      "#####RRR##",
      "#######RC#",
      "#######R##",
      "#######R##",
      "######LB##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_039: {
    id: "random_039",
    name: "Random Dungeon 039",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##E#######",
      "##R#######",
      "##R#######",
      "##R#######",
      "##RRRC####",
      "MRM#######",
      "#R#R######",
      "#RRRR#####",
      "#R##RRMR##",
      "#C#####R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_040: {
    id: "random_040",
    name: "Random Dungeon 040",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "###E######",
      "###R######",
      "###R######",
      "###R######",
      "##MR######",
      "###RRRRMR#",
      "###M####R#",
      "###N###RM#",
      "#######R##",
      "#######R##",
      "#######M##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_041: {
    id: "random_041",
    name: "Random Dungeon 041",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "####E#####",
      "####R#####",
      "####R#####",
      "##RRRRRR##",
      "#####R#RRC",
      "#######M##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_042: {
    id: "random_042",
    name: "Random Dungeon 042",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "#E########",
      "#R########",
      "#R########",
      "#MR#######",
      "##R#######",
      "##R#######",
      "##R#######",
      "##R#######",
      "##R###N###",
      "CRR###R###",
      "##RRRRRR##",
      "#######R##",
      "#######R##",
      "#######M##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_043: {
    id: "random_043",
    name: "Random Dungeon 043",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "#####E####",
      "#####R####",
      "#####R####",
      "#####R####",
      "####RR####",
      "####R#####",
      "####R#####",
      "####R#####",
      "####RRRR##",
      "#####R#RC#",
      "#####M#R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######M##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_044: {
    id: "random_044",
    name: "Random Dungeon 044",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "###E######",
      "###R######",
      "###R######",
      "###R######",
      "###RRR####",
      "#####RRN##",
      "#####R####",
      "#####R####",
      "##CRRR####",
      "#####R####",
      "####MR####",
      "#####RRR##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_045: {
    id: "random_045",
    name: "Random Dungeon 045",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "####E#####",
      "####R#####",
      "####R#C###",
      "####R#R###",
      "####RRR###",
      "######RRC#",
      "######R###",
      "######R###",
      "######R###",
      "######RR##",
      "#######RRC",
      "#######R##",
      "#######M##",
      "######LR##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_046: {
    id: "random_046",
    name: "Random Dungeon 046",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "########E#",
      "########R#",
      "#####M##R#",
      "#####RRRR#",
      "####MR####",
      "#####R####",
      "#####M####",
      "#####R####",
      "#####R####",
      "#####R####",
      "#####R####",
      "#####R####",
      "#####RRR##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_047: {
    id: "random_047",
    name: "Random Dungeon 047",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#####E####",
      "#####R####",
      "#####R####",
      "#####RRRR#",
      "########R#",
      "########R#",
      "######CRR#",
      "########R#",
      "########M#",
      "########R#",
      "#######CR#",
      "########R#",
      "########M#",
      "#######RR#",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_048: {
    id: "random_048",
    name: "Random Dungeon 048",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "#######E##",
      "#######R##",
      "#######R##",
      "####CRMR##",
      "#######R##",
      "####RRRR##",
      "####R#####",
      "####R#####",
      "####RRMR##",
      "#######RMC",
      "#######R##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_049: {
    id: "random_049",
    name: "Random Dungeon 049",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#####E####",
      "#####R####",
      "#####R####",
      "#####R####",
      "#RRMRR####",
      "#R########",
      "#R########",
      "#R########",
      "MR########",
      "#RRRR#####",
      "####R#####",
      "####RRM###",
      "###CR#####",
      "####MRRR##",
      "#####C#R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_050: {
    id: "random_050",
    name: "Random Dungeon 050",
    location: "random_pool",
    length: "short",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "#######E##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#####C#R##",
      "#####RRR##",
      "#####R####",
      "#####R####",
      "##RRMRRC##",
      "##R#######",
      "##RRRRRMM#",
      "####M##R##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_051: {
    id: "random_051",
    name: "Random Dungeon 051",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "########E#",
      "########R#",
      "####C#R#R#",
      "####R#R#R#",
      "####M#R#R#",
      "####RMRMR#",
      "#RRRM#####",
      "####RRRR##",
      "#####R#MR#",
      "#####R##R#",
      "#####C#RR#",
      "#######M##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_052: {
    id: "random_052",
    name: "Random Dungeon 052",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "####M#E###",
      "####R#R###",
      "####R#R###",
      "###RRMR###",
      "#NRR######",
      "###R######",
      "###M######",
      "###R######",
      "#CRR######",
      "###MRRM###",
      "###R######",
      "###RRM####",
      "##RR######",
      "##R#######",
      "##RMRRRR##",
      "##M####B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_053: {
    id: "random_053",
    name: "Random Dungeon 053",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "#######E##",
      "#######R##",
      "#######M##",
      "#####CRR##",
      "#######R##",
      "###MRMRM##",
      "#######R##",
      "####CRRR##",
      "#######R##",
      "#######R##",
      "#######M##",
      "####CRMR##",
      "#######R##",
      "#######M##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_054: {
    id: "random_054",
    name: "Random Dungeon 054",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "######E###",
      "######R###",
      "######M###",
      "###C##MM##",
      "###R##R###",
      "NRRRRRR###",
      "##R###N###",
      "##R#M#####",
      "##R#R#####",
      "##RMRRRR##",
      "###C#N#B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_055: {
    id: "random_055",
    name: "Random Dungeon 055",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "#####E####",
      "#####R####",
      "#####R####",
      "##MRMRRM##",
      "#######R##",
      "#######R##",
      "##MRRRRR##",
      "CRM#######",
      "##R###C###",
      "RRR###M###",
      "##RRRRRM##",
      "#######R##",
      "#######R##",
      "####NMRM##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_056: {
    id: "random_056",
    name: "Random Dungeon 056",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##E#######",
      "##R#######",
      "##R#######",
      "##RMRC####",
      "###R######",
      "###R#C####",
      "###R#R####",
      "NRMR#M####",
      "###RRRRR##",
      "####R##RRN",
      "####C##R##",
      "#######R##",
      "#######M##",
      "#######M##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_057: {
    id: "random_057",
    name: "Random Dungeon 057",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "#E########",
      "#R########",
      "#R########",
      "#R########",
      "#R########",
      "#RRRRC####",
      "#R########",
      "#RR#######",
      "##R#R#####",
      "##RRRR####",
      "#####RRRRC",
      "#####R####",
      "##CMRRRM##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_058: {
    id: "random_058",
    name: "Random Dungeon 058",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "###E######",
      "###R##C###",
      "###R##R###",
      "###R##R###",
      "###RMMRRR#",
      "###M####M#",
      "###M#M##R#",
      "#####R##R#",
      "###RRRRMR#",
      "#MRR######",
      "###RRRRMC#",
      "###R#R#R##",
      "###R#R#R##",
      "###C#C#R##",
      "#######M##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_059: {
    id: "random_059",
    name: "Random Dungeon 059",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "###E######",
      "###R######",
      "###M######",
      "###M######",
      "#RRRR##R##",
      "####R##R##",
      "#CRRMRRRR#",
      "########R#",
      "####MRRMR#",
      "#######M##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_060: {
    id: "random_060",
    name: "Random Dungeon 060",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "########E#",
      "########R#",
      "########R#",
      "#####NRRR#",
      "########R#",
      "########R#",
      "####NRMRM#",
      "#######R##",
      "#####CRM##",
      "#######MRC",
      "#######R##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_061: {
    id: "random_061",
    name: "Random Dungeon 061",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##E#######",
      "##R#######",
      "##R#######",
      "CRR###N###",
      "##RC##R#M#",
      "##R###R#R#",
      "##RRMRRRR#",
      "###R####R#",
      "###R###RM#",
      "###R###R##",
      "###C###S##",
      "##########",
      "##########"
    ]
  },
  random_062: {
    id: "random_062",
    name: "Random Dungeon 062",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#####E####",
      "#####R####",
      "#####M####",
      "#####RRRC#",
      "####MR####",
      "#####R####",
      "###RRMM###",
      "RMRR######",
      "###RRRRM##",
      "###C#R#R##",
      "#####M#B##",
      "#####C#S##",
      "##########",
      "##########"
    ]
  },
  random_063: {
    id: "random_063",
    name: "Random Dungeon 063",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "########E#",
      "########R#",
      "########R#",
      "####CRRRR#",
      "########R#",
      "####RRRRM#",
      "##NRR###R#",
      "####M###M#",
      "####RRR###",
      "######R###",
      "######RRC#",
      "#MRRMRR###",
      "######RR##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_064: {
    id: "random_064",
    name: "Random Dungeon 064",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#E########",
      "#R#C######",
      "#R#R######",
      "CRRRR#####",
      "####R#####",
      "#MRMR#####",
      "####R#####",
      "####RRRR##",
      "####M##R##",
      "####M##R##",
      "####C##R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_065: {
    id: "random_065",
    name: "Random Dungeon 065",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##E#######",
      "##R#######",
      "##R#######",
      "##RRC#####",
      "#MR#######",
      "##R#######",
      "RRRR######",
      "###MMRC###",
      "##RR######",
      "MMR#######",
      "##RRRRM###",
      "####M#####",
      "##NRRRRM##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_066: {
    id: "random_066",
    name: "Random Dungeon 066",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##E#######",
      "##R#######",
      "##R#C#####",
      "CMR#R#####",
      "##M#R#####",
      "##RRR#####",
      "####RRC###",
      "####R#####",
      "#CRRR#####",
      "####RRR###",
      "######RR##",
      "#######R##",
      "#######MMR",
      "######CR##",
      "#######R##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_067: {
    id: "random_067",
    name: "Random Dungeon 067",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "######E###",
      "######R###",
      "######M###",
      "######RN##",
      "####NRR###",
      "######R###",
      "##MRRRRRM#",
      "#####R####",
      "##MRRMRR##",
      "#######R##",
      "######RR##",
      "##NRRRR###",
      "######M###",
      "######MR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_068: {
    id: "random_068",
    name: "Random Dungeon 068",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "####E#####",
      "####R#####",
      "####R#####",
      "####R#####",
      "####R#R###",
      "####R#M###",
      "##MRRRRR##",
      "#######R##",
      "####NRRR##",
      "#######R##",
      "###RRMRM##",
      "###R######",
      "###R######",
      "###RRRMM##",
      "#####R#R##",
      "#####M#B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_069: {
    id: "random_069",
    name: "Random Dungeon 069",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "###E######",
      "###R######",
      "###R######",
      "###MRRRC##",
      "###R######",
      "#CRM##C###",
      "###RRRR###",
      "######RMN#",
      "######R###",
      "##RRMRM###",
      "##R#######",
      "#MRRMRRM##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_070: {
    id: "random_070",
    name: "Random Dungeon 070",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "#E########",
      "#R########",
      "#R########",
      "#R########",
      "#RMRMM#M##",
      "#M###R#R##",
      "##N##RMRR#",
      "##R#C###R#",
      "##R#R###R#",
      "##MRMRMRR#",
      "NRM#######",
      "##RRRRMR##",
      "##R####R##",
      "##R####B##",
      "##C####S##",
      "##########",
      "##########"
    ]
  },
  random_071: {
    id: "random_071",
    name: "Random Dungeon 071",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "###E######",
      "###R######",
      "###R######",
      "#CMR######",
      "###RMMC###",
      "#CRR######",
      "###MRRRC##",
      "###R######",
      "MMRRRRRR##",
      "####M##R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_072: {
    id: "random_072",
    name: "Random Dungeon 072",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#######E##",
      "#######R##",
      "#######R##",
      "#######MRN",
      "######RR##",
      "###MRRR###",
      "######R###",
      "##CRRRR###",
      "######RM##",
      "###RRRM###",
      "##RR######",
      "CMR#######",
      "##R##C####",
      "##RRMMRR##",
      "###C###B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_073: {
    id: "random_073",
    name: "Random Dungeon 073",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##E#######",
      "##R###N###",
      "##R###M###",
      "NRR###R###",
      "##M###R###",
      "##RRRRR###",
      "######M###",
      "##RRRRR###",
      "#CM#######",
      "##RMRRRR##",
      "####R##R##",
      "####C##RMN",
      "#######M##",
      "#######M##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_074: {
    id: "random_074",
    name: "Random Dungeon 074",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "####E#####",
      "####R#####",
      "####R#####",
      "####M#####",
      "####RRR###",
      "######RMRN",
      "######R###",
      "######R###",
      "####RMRC##",
      "####M#####",
      "###MR#####",
      "###M##N###",
      "###RRRRR##",
      "#####M#R##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_075: {
    id: "random_075",
    name: "Random Dungeon 075",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "#######E##",
      "#######R##",
      "#######M##",
      "####NRRR##",
      "#######MRR",
      "#######R##",
      "####CRMR##",
      "######M###",
      "###RRRRRC#",
      "##RR######",
      "##R#######",
      "#CMRRRRR##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_076: {
    id: "random_076",
    name: "Random Dungeon 076",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "####E#####",
      "####R#####",
      "####M#####",
      "####R#####",
      "####R##C##",
      "####R##R##",
      "####MRRRR#",
      "##M#####M#",
      "#RMRRRRRR#",
      "#R######R#",
      "#R######M#",
      "#RR#C#####",
      "##RRMRRR##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_077: {
    id: "random_077",
    name: "Random Dungeon 077",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "#######E##",
      "#####C#R##",
      "#####R#M##",
      "#####M#R##",
      "###RRMMR##",
      "MMRR######",
      "###M######",
      "###RRRRMR#",
      "####C###M#",
      "######C#R#",
      "##RRRRRRM#",
      "##M#######",
      "##MRRMRR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_078: {
    id: "random_078",
    name: "Random Dungeon 078",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##M#####E#",
      "##R#####R#",
      "##M#####R#",
      "##RRRRRMR#",
      "##R##M####",
      "##M#######",
      "##M#C#####",
      "##RRRR####",
      "#####R####",
      "#####R####",
      "#####R####",
      "#####R####",
      "#####R####",
      "#####M####",
      "####NRRR##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_079: {
    id: "random_079",
    name: "Random Dungeon 079",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "#####E####",
      "#####R####",
      "#####R####",
      "#####M####",
      "#####RC###",
      "####RR####",
      "####M#####",
      "####RC####",
      "####R#####",
      "###MR#C###",
      "###R##R###",
      "###MMRRMRN",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_080: {
    id: "random_080",
    name: "Random Dungeon 080",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#######E##",
      "#######R##",
      "###M#M#M##",
      "#N#M#R#R##",
      "#R#R#R#MRC",
      "#RRRRRRR##",
      "#R########",
      "#RRMRRRR##",
      "#M#R###M##",
      "#C#C###R##",
      "#######R##",
      "#####RRR##",
      "#######M##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_081: {
    id: "random_081",
    name: "Random Dungeon 081",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#####E####",
      "#####R####",
      "#####R####",
      "#####R####",
      "#####M####",
      "##CMRR####",
      "#####RRRMM",
      "#####R####",
      "##MRRRMRRC",
      "######M###",
      "#####LMR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_082: {
    id: "random_082",
    name: "Random Dungeon 082",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "###E######",
      "###R######",
      "###M######",
      "CRRR######",
      "###R######",
      "###RMC####",
      "###R######",
      "###R######",
      "###R######",
      "CRRR######",
      "###R##R###",
      "###R##R###",
      "###R##R###",
      "###RRMRMM#",
      "###R###R##",
      "###R###R##",
      "###C###B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_083: {
    id: "random_083",
    name: "Random Dungeon 083",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "#######E##",
      "#######R##",
      "#######R##",
      "#####N#M##",
      "#####RRR##",
      "#####R####",
      "##CMRR####",
      "#####RRR##",
      "#######RC#",
      "#######R##",
      "#####MRR##",
      "#######R##",
      "#######RC#",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_084: {
    id: "random_084",
    name: "Random Dungeon 084",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "########E#",
      "########R#",
      "########M#",
      "########M#",
      "##C###NMR#",
      "##M#####M#",
      "#RRRRRMMR#",
      "#R########",
      "#RRRRMMML#",
      "#R###R#B##",
      "#C###C#S##",
      "##########",
      "##########"
    ]
  },
  random_085: {
    id: "random_085",
    name: "Random Dungeon 085",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##E#######",
      "##R#######",
      "##M#######",
      "##RRRN####",
      "##R#######",
      "CMRR######",
      "###RRR####",
      "###R######",
      "###R######",
      "CRRR######",
      "#R####M###",
      "#R####R###",
      "#RMMMRMM##",
      "#R##M##R##",
      "#R##R##R##",
      "####M##S##",
      "##########",
      "##########"
    ]
  },
  random_086: {
    id: "random_086",
    name: "Random Dungeon 086",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "#######E##",
      "#######R##",
      "#######R##",
      "###RRRRR##",
      "###M###R##",
      "###RMC#C##",
      "###M######",
      "###RMM####",
      "#####RMR##",
      "#####R#RRR",
      "#####M#R##",
      "#####N#R##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_087: {
    id: "random_087",
    name: "Random Dungeon 087",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "###E######",
      "#C#R######",
      "#R#R######",
      "#RRRRC####",
      "#R#####M##",
      "#MRRRR#R##",
      "#####R#R##",
      "#####RRMRN",
      "#####R##R#",
      "#####R#MR#",
      "#####R#R##",
      "#####N#M##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_088: {
    id: "random_088",
    name: "Random Dungeon 088",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "########E#",
      "########R#",
      "########R#",
      "########R#",
      "####C#C#R#",
      "####R#M#R#",
      "#MRRRRRRR#",
      "#M########",
      "#RRRRRRRR#",
      "#M######R#",
      "#C###NRRR#",
      "########R#",
      "#RRMRRRMR#",
      "#R########",
      "#RRRRMRR##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_089: {
    id: "random_089",
    name: "Random Dungeon 089",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "#E###R####",
      "#R###R####",
      "#R#N#R####",
      "#R#R#R####",
      "#R#R#M####",
      "#MRMRRMRM#",
      "##R#####M#",
      "####RRRRR#",
      "#RRRR#R#M#",
      "NM##R###M#",
      "#R##C###C#",
      "#R########",
      "#RRRRMRR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_090: {
    id: "random_090",
    name: "Random Dungeon 090",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "###E######",
      "###R######",
      "###R######",
      "MRRRRRMMC#",
      "##R#######",
      "##M#######",
      "##M###N###",
      "##R###R###",
      "##R###R###",
      "##RRMRMR##",
      "###R###R##",
      "###R###R##",
      "###R###RM#",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_091: {
    id: "random_091",
    name: "Random Dungeon 091",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##E#######",
      "##RL######",
      "##R#######",
      "##RM######",
      "#RM#######",
      "NR########",
      "#MMC######",
      "#R########",
      "#RR#######",
      "##R#######",
      "##MRRMMR##",
      "###M#N#R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_092: {
    id: "random_092",
    name: "Random Dungeon 092",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "#####E####",
      "#####R####",
      "#####R####",
      "CRRRMR####",
      "#####R####",
      "###RRRRRC#",
      "CMRR######",
      "###M######",
      "##RR#N####",
      "MRM##R####",
      "##MRMRRR##",
      "##M#R##R##",
      "##R#R##B##",
      "##N#C##S##",
      "##########",
      "##########"
    ]
  },
  random_093: {
    id: "random_093",
    name: "Random Dungeon 093",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##E#######",
      "##R#C#####",
      "##R#R#####",
      "##R#R#####",
      "##R#R#####",
      "##RMMR####",
      "###R#R####",
      "###M#RRR##",
      "#######R##",
      "###RRRRR##",
      "###R######",
      "###M######",
      "##MR######",
      "###MRMRR##",
      "####R##R##",
      "####R##R##",
      "####M##R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_094: {
    id: "random_094",
    name: "Random Dungeon 094",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "######E###",
      "######R###",
      "######R###",
      "###MRRM###",
      "######R###",
      "####C#RRR#",
      "####R#R###",
      "####RRR###",
      "####M#R###",
      "####R#M###",
      "####R#####",
      "####R#####",
      "#NRMR#####",
      "####RR####",
      "#####RRR##",
      "#####C#B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_095: {
    id: "random_095",
    name: "Random Dungeon 095",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##E#######",
      "##R##M####",
      "##R##R####",
      "##MRRRR###",
      "###R##R###",
      "###C##M###",
      "######R###",
      "######R###",
      "#CRRRRR###",
      "######R###",
      "##RRMMR###",
      "##R#######",
      "##R#######",
      "##RRRRRR##",
      "##M####R##",
      "##M####R##",
      "##N####S##",
      "##########",
      "##########"
    ]
  },
  random_096: {
    id: "random_096",
    name: "Random Dungeon 096",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "###E######",
      "###R######",
      "###R######",
      "#CRR######",
      "###RRRRM##",
      "###M######",
      "##MR######",
      "##R#######",
      "#MR#######",
      "##R#######",
      "##RRRM####",
      "##R#######",
      "##MRR#####",
      "####MRRR##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_097: {
    id: "random_097",
    name: "Random Dungeon 097",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#E########",
      "#R########",
      "#M########",
      "#M########",
      "#MRRMN####",
      "##M#######",
      "#RR##C####",
      "##RRRRR###",
      "##R#R#RM##",
      "##R#R##R##",
      "##R#M##R##",
      "##N####R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_098: {
    id: "random_098",
    name: "Random Dungeon 098",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "######E###",
      "######R###",
      "######M###",
      "######RRR#",
      "######R###",
      "##CRRRMRM#",
      "#######R##",
      "#####MRRR#",
      "########R#",
      "#######RR#",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_099: {
    id: "random_099",
    name: "Random Dungeon 099",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "####E#####",
      "####R#####",
      "####R#####",
      "###MR#####",
      "###R######",
      "###R######",
      "###R######",
      "#RRR######",
      "#R########",
      "#RRRC#####",
      "#M#####M##",
      "#RRRRRMR##",
      "#R#C###R##",
      "#R#####R##",
      "#M#####R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_100: {
    id: "random_100",
    name: "Random Dungeon 100",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "########E#",
      "########R#",
      "########R#",
      "########M#",
      "#######RM#",
      "#######M##",
      "###NRRRR##",
      "#######R##",
      "#######R##",
      "###C###RC#",
      "###R###R##",
      "###R###R##",
      "###RRMRRC#",
      "###R######",
      "##CRRMRR##",
      "####M##R##",
      "####C##B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_101: {
    id: "random_101",
    name: "Random Dungeon 101",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "###E######",
      "###R######",
      "###M######",
      "###R######",
      "###RMM####",
      "#CRR######",
      "###RMRRM##",
      "###R######",
      "###R######",
      "#MRRMR####",
      "#####RRR##",
      "#####M#R##",
      "#####N#R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_102: {
    id: "random_102",
    name: "Random Dungeon 102",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#######E##",
      "#######R##",
      "#######R##",
      "#######M##",
      "#####MRR##",
      "#######R##",
      "###RMRRR##",
      "#RRR###M##",
      "###R###C##",
      "###R######",
      "#RRRRMC###",
      "#R########",
      "NR########",
      "#RRMRRRR##",
      "##R####B##",
      "##R####S##",
      "##########",
      "##########"
    ]
  },
  random_103: {
    id: "random_103",
    name: "Random Dungeon 103",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "#######E##",
      "#######R##",
      "#######R##",
      "#####MRMRN",
      "#####R####",
      "#####MRRRC",
      "#####R####",
      "#####RN###",
      "#####R####",
      "#RRMRM####",
      "#R########",
      "#R########",
      "#RRMRRRR##",
      "#####R#R##",
      "####LM#R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_104: {
    id: "random_104",
    name: "Random Dungeon 104",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##E#######",
      "##R#######",
      "##R#######",
      "##R###C###",
      "MRR###R###",
      "##R#C#R###",
      "##RRMRRR##",
      "#######R##",
      "##RRRRRR##",
      "##R#######",
      "#CR#######",
      "##R#######",
      "##R#M#####",
      "##R#R#####",
      "##RRMRMR##",
      "#####M#B##",
      "#####M#S##",
      "##########",
      "##########"
    ]
  },
  random_105: {
    id: "random_105",
    name: "Random Dungeon 105",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#M##E#####",
      "#R##R#####",
      "#R##R#####",
      "#RRRR#####",
      "#R#R######",
      "#R#C######",
      "#RM#######",
      "##RRRRMRC#",
      "#####R####",
      "#NRMRR####",
      "#####RMR##",
      "#####M#RRM",
      "#####M#R##",
      "#####R#R##",
      "#####N#R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_106: {
    id: "random_106",
    name: "Random Dungeon 106",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "#######E##",
      "#######R##",
      "#######R##",
      "#######R##",
      "###CMRMR##",
      "#C#####R##",
      "#R###RRMRC",
      "#M###R####",
      "#R###R####",
      "#RRRRR####",
      "#R########",
      "#RRR######",
      "#R########",
      "#MMRRRRR##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_107: {
    id: "random_107",
    name: "Random Dungeon 107",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##E#######",
      "##R#######",
      "##M#######",
      "CRRMMM####",
      "###R######",
      "###RMM####",
      "#MRR######",
      "###R####N#",
      "###R##M#R#",
      "###MMRRRR#",
      "########M#",
      "#######RR#",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_108: {
    id: "random_108",
    name: "Random Dungeon 108",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "#E########",
      "#R########",
      "#R########",
      "#R########",
      "#RRR######",
      "#R#R######",
      "#R#RRMC###",
      "#M##R#####",
      "####R#####",
      "#RRMR#####",
      "####M#####",
      "#NRRRRRR##",
      "###L###B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_109: {
    id: "random_109",
    name: "Random Dungeon 109",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "######E###",
      "######R###",
      "######R###",
      "######R###",
      "#N####R###",
      "#RRRRRM###",
      "#R########",
      "#R########",
      "#RRRM#####",
      "#M########",
      "#R###M####",
      "#RRRRR####",
      "###R#RRM##",
      "###R###M##",
      "###R###M##",
      "###N###R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_110: {
    id: "random_110",
    name: "Random Dungeon 110",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "#C###E####",
      "#R###R####",
      "#M#M#M####",
      "#R#R#M####",
      "#RRRRRMRC#",
      "#R########",
      "#RRRRRRM##",
      "#######RM#",
      "#RRRMRRR##",
      "MM########",
      "#R########",
      "#RRMRRRR##",
      "##M#R##R##",
      "####C##B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_111: {
    id: "random_111",
    name: "Random Dungeon 111",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##E#######",
      "##R#######",
      "##R#######",
      "##R#######",
      "##RMRN####",
      "##R#######",
      "#RM#######",
      "#R########",
      "#RN##C####",
      "#R###R####",
      "#RRRRRR###",
      "##R#R#R###",
      "##R#M#R###",
      "##R#C#MR##",
      "##C####M##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_112: {
    id: "random_112",
    name: "Random Dungeon 112",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#####E####",
      "#####R####",
      "#####R####",
      "#####RN###",
      "#####R####",
      "CRRRRR##M#",
      "#####RR#R#",
      "######R#R#",
      "#####MRRR#",
      "########RC",
      "######MRR#",
      "###CMRR#R#",
      "######R#N#",
      "######RM##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_113: {
    id: "random_113",
    name: "Random Dungeon 113",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#E########",
      "#R########",
      "#R########",
      "#R#L######",
      "#MRM####M#",
      "#R##M#C#R#",
      "#RRRMRRRR#",
      "#R#R#R##M#",
      "#C#C###RR#",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_114: {
    id: "random_114",
    name: "Random Dungeon 114",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#######E##",
      "##M####R##",
      "##R####R##",
      "##R#C##R##",
      "##R#R##R##",
      "#RRMRRRR##",
      "#M########",
      "#R########",
      "#RRRC#####",
      "#R###M####",
      "#MMM#R####",
      "###MRRRR##",
      "###R###R##",
      "###R###M##",
      "###M###B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_115: {
    id: "random_115",
    name: "Random Dungeon 115",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#E########",
      "#R########",
      "#R###C####",
      "#R###R####",
      "#R#N#R#M##",
      "#RRRRRMRRC",
      "##C###R#R#",
      "######M#R#",
      "#######RR#",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_116: {
    id: "random_116",
    name: "Random Dungeon 116",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#######E##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######R##",
      "##C##RRR##",
      "##M##R#R##",
      "##RMRM#R##",
      "##R####N##",
      "##R#N#####",
      "##RRR#####",
      "##M#RMRR##",
      "##R####R##",
      "##R####R##",
      "##C####B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_117: {
    id: "random_117",
    name: "Random Dungeon 117",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#E########",
      "#R########",
      "#R########",
      "#RRRM#####",
      "#R########",
      "CMRRMMR###",
      "##R#M#R###",
      "##R#R#RM##",
      "##R#N#R###",
      "##C###R###",
      "####RRR###",
      "######RR##",
      "#######R##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_118: {
    id: "random_118",
    name: "Random Dungeon 118",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#######E##",
      "#####N#R##",
      "#####R#R##",
      "#####R#RC#",
      "#####R#R##",
      "##N##R#R##",
      "##MMRRRMC#",
      "##R#######",
      "MRRRMRMR##",
      "###R###B##",
      "###M###S##",
      "##########",
      "##########"
    ]
  },
  random_119: {
    id: "random_119",
    name: "Random Dungeon 119",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##C##E####",
      "##R##R####",
      "##R##R####",
      "##R#CR####",
      "##R##MRN##",
      "##RRMM####",
      "##R##R####",
      "##R##R####",
      "CRR##N####",
      "##M#######",
      "##M#######",
      "CRR#######",
      "##RMRRMR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_120: {
    id: "random_120",
    name: "Random Dungeon 120",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "#E########",
      "#R########",
      "#R########",
      "#RRRN#####",
      "#M####N###",
      "#M####R###",
      "#RRMR#R###",
      "##M#RRR###",
      "####R#R###",
      "####C#R###",
      "######M###",
      "######R###",
      "######R###",
      "######RR##",
      "#######BL#",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_121: {
    id: "random_121",
    name: "Random Dungeon 121",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "#######E##",
      "#######R##",
      "#######R##",
      "#######M##",
      "#######RC#",
      "####C##R##",
      "####R##R##",
      "####R##R##",
      "##RRRMRM##",
      "##R#######",
      "##R##M####",
      "##RR#R####",
      "###RMR####",
      "###R#RRR##",
      "###R###M##",
      "###M###R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_122: {
    id: "random_122",
    name: "Random Dungeon 122",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "########E#",
      "########R#",
      "########R#",
      "####NRMRR#",
      "########R#",
      "###CRRMRR#",
      "######R###",
      "#####MMRM#",
      "#MRRRR####",
      "#####MRMC#",
      "##CRRR####",
      "#####MR###",
      "######MM##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_123: {
    id: "random_123",
    name: "Random Dungeon 123",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "######E###",
      "####C#R###",
      "####R#R###",
      "####R#RM##",
      "###RMRR###",
      "###R######",
      "##CR######",
      "###RRM####",
      "###R#M####",
      "###R#RMR##",
      "###C###R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_124: {
    id: "random_124",
    name: "Random Dungeon 124",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "#E########",
      "#R########",
      "#R########",
      "#RRRRRR###",
      "#R#R##RRRC",
      "#C#N#RR###",
      "#####R####",
      "#MRMRR####",
      "#####M####",
      "####MMM###",
      "######MRR#",
      "######R###",
      "######RRRM",
      "#######R##",
      "#######R##",
      "#######M##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_125: {
    id: "random_125",
    name: "Random Dungeon 125",
    location: "random_pool",
    length: "medium",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "###E######",
      "###R######",
      "###R##M###",
      "###R##R###",
      "###R##R###",
      "###RRRRR##",
      "####R##MRM",
      "####C##R##",
      "#######RRC",
      "####CRRM##",
      "######R###",
      "#RMRRRR###",
      "#M########",
      "#MRRRRRR##",
      "####M##M##",
      "#######R##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_126: {
    id: "random_126",
    name: "Random Dungeon 126",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "#E####C###",
      "#R####R###",
      "#R##M#R###",
      "#M##R#R###",
      "#RR#R#R#C#",
      "##R#R#M#R#",
      "MRRMRRR#R#",
      "###M##MMM#",
      "###N##R#R#",
      "######R#R#",
      "######R#R#",
      "######R#R#",
      "######R#R#",
      "######N#M#",
      "#######RR#",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_127: {
    id: "random_127",
    name: "Random Dungeon 127",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "###E##M###",
      "###R##R###",
      "###R##R###",
      "###R##R###",
      "###R##R###",
      "###RRMRMRN",
      "##LR###M##",
      "###C###R##",
      "####CRRMR#",
      "########R#",
      "#######RR#",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_128: {
    id: "random_128",
    name: "Random Dungeon 128",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##E#######",
      "##R#R#####",
      "##R#R#M###",
      "CRR#R#R###",
      "##M#R#R###",
      "##M#R#R###",
      "##RRRRMR##",
      "#######R##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_129: {
    id: "random_129",
    name: "Random Dungeon 129",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "###E######",
      "###R######",
      "###M######",
      "###RRRRRN#",
      "MMRR######",
      "###RRMRRRC",
      "#####R####",
      "CMRRRRRR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_130: {
    id: "random_130",
    name: "Random Dungeon 130",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##E#######",
      "##R##N####",
      "##R##R####",
      "CMM##M####",
      "##M##M####",
      "##R##R####",
      "NRRRMR####",
      "#####R####",
      "#CRRRRRR##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_131: {
    id: "random_131",
    name: "Random Dungeon 131",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "###E######",
      "###R######",
      "###R######",
      "###RMN####",
      "###R######",
      "CRRR######",
      "###MRRRRC#",
      "####M#####",
      "####RRMRC#",
      "CRMRR#####",
      "####MR####",
      "#####MRR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_132: {
    id: "random_132",
    name: "Random Dungeon 132",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##M#######",
      "##R#######",
      "##R#E#####",
      "##R#R#####",
      "##R#R#####",
      "##RMR#####",
      "##R#######",
      "##RRRRM###",
      "##R#######",
      "##M#######",
      "##RRMRRM##",
      "#######R##",
      "####RRRR##",
      "####R#####",
      "#NRRR#####",
      "####RRRR##",
      "#####R#B##",
      "#####N#S##",
      "##########",
      "##########"
    ]
  },
  random_133: {
    id: "random_133",
    name: "Random Dungeon 133",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#####C####",
      "###C#R#E##",
      "###R#R#R##",
      "##LR#M#M##",
      "###R#RRR##",
      "###R#R####",
      "###RMR####",
      "CRMM######",
      "###RMRRR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_134: {
    id: "random_134",
    name: "Random Dungeon 134",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "###E######",
      "###R######",
      "###R######",
      "MMRR######",
      "###R######",
      "##MRRRMM##",
      "##R#######",
      "##RRRRRMRC",
      "##R#R#####",
      "##M#RRRR##",
      "##C##R#B##",
      "#####C#S##",
      "##########",
      "##########"
    ]
  },
  random_135: {
    id: "random_135",
    name: "Random Dungeon 135",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#E########",
      "#R########",
      "#R########",
      "#R########",
      "#M##N#####",
      "#RM#R#####",
      "##M#R#####",
      "##RRRMRR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_136: {
    id: "random_136",
    name: "Random Dungeon 136",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#######E##",
      "#####N#R##",
      "#####R#R##",
      "#####R#M##",
      "#####MRRRC",
      "#MRMRR####",
      "#####R####",
      "#MMRMRRR##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_137: {
    id: "random_137",
    name: "Random Dungeon 137",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "########E#",
      "########R#",
      "######M#R#",
      "######R#M#",
      "######RRM#",
      "###MRRR###",
      "######RR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_138: {
    id: "random_138",
    name: "Random Dungeon 138",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "######E###",
      "##C#C#R###",
      "##R#R#R###",
      "#RMMRMR###",
      "#R########",
      "#RRR######",
      "#R#RRRRM##",
      "#R#R######",
      "#N#RRRM###",
      "###R######",
      "#RRRRRN###",
      "#M########",
      "#R########",
      "#MRMRMRR##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_139: {
    id: "random_139",
    name: "Random Dungeon 139",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "######E###",
      "######R###",
      "######M###",
      "##MRRRR###",
      "######RRM#",
      "####MRR###",
      "######R###",
      "######RR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_140: {
    id: "random_140",
    name: "Random Dungeon 140",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "######N###",
      "####C#R###",
      "##E#R#R###",
      "##R#R#R###",
      "##R#R#R###",
      "CMM#R#R###",
      "##R#R#M###",
      "##MRRMMR##",
      "###R###R##",
      "###M###B##",
      "###M###S##",
      "##########",
      "##########"
    ]
  },
  random_141: {
    id: "random_141",
    name: "Random Dungeon 141",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "######C###",
      "######M###",
      "######R#E#",
      "######R#R#",
      "######M#R#",
      "#MRMRRRMR#",
      "#R######R#",
      "#RRRR###R#",
      "#R######R#",
      "#R###N##N#",
      "#RRR#R#N##",
      "#R#M#M#R##",
      "#M#MRMRR##",
      "#R##R##M##",
      "#R##M##R##",
      "#R##M##M##",
      "#R#####R##",
      "#M#####S##",
      "##########",
      "##########"
    ]
  },
  random_142: {
    id: "random_142",
    name: "Random Dungeon 142",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "######E###",
      "######R#M#",
      "######R#R#",
      "CRRRRRR#R#",
      "######R#R#",
      "##M#C#RMR#",
      "##R#M###R#",
      "##R#R#RRR#",
      "##RRRMM#R#",
      "##R#####R#",
      "#RRRRRC#R#",
      "#M######N#",
      "#RRMRRR###",
      "#R####RR##",
      "#M#####B##",
      "#C#####S##",
      "##########",
      "##########"
    ]
  },
  random_143: {
    id: "random_143",
    name: "Random Dungeon 143",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "######E###",
      "######R###",
      "######R###",
      "#####RRMRN",
      "#####R####",
      "#CRRRM####",
      "#####RMR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_144: {
    id: "random_144",
    name: "Random Dungeon 144",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "######E###",
      "######R###",
      "##C###R###",
      "##R#CMR###",
      "##M###R###",
      "#RRRRRRMRC",
      "#M########",
      "#RRRMRRM##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_145: {
    id: "random_145",
    name: "Random Dungeon 145",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "###E######",
      "###R######",
      "###R######",
      "#NRR######",
      "###RRMMRRN",
      "####M#####",
      "##RRR#####",
      "CRR#######",
      "##RR######",
      "###RRC####",
      "###R###C##",
      "###M###R##",
      "###MRRRRR#",
      "###R#R##R#",
      "###R#R#RR#",
      "###R#C#R##",
      "###R###R##",
      "###C###S##",
      "##########",
      "##########"
    ]
  },
  random_146: {
    id: "random_146",
    name: "Random Dungeon 146",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "###E######",
      "###R######",
      "###R######",
      "#MRR######",
      "###R######",
      "###R#M####",
      "###R#R####",
      "###R#R####",
      "###RRRRR##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_147: {
    id: "random_147",
    name: "Random Dungeon 147",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#####E####",
      "#####R####",
      "#####R####",
      "###MRM####",
      "#####RRRRC",
      "#CRRRR####",
      "#####RRR##",
      "#######R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_148: {
    id: "random_148",
    name: "Random Dungeon 148",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "#####E####",
      "#####R####",
      "#####M####",
      "#MRRRR####",
      "#####RMRRM",
      "#####M####",
      "####RMRMR#",
      "##NRM#####",
      "####RR####",
      "#####RRR##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_149: {
    id: "random_149",
    name: "Random Dungeon 149",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "########M#",
      "######E#M#",
      "####N#R#M#",
      "##N#R#R#R#",
      "##R#R#R#R#",
      "##M#R#MRR#",
      "##R#R###M#",
      "##MMRRRRR#",
      "##M#######",
      "##RRRRRRC#",
      "#####M####",
      "#RMRRR####",
      "###R######",
      "###RRRMR##",
      "###R###R##",
      "###R###R##",
      "#######S##",
      "##########",
      "##########"
    ]
  },
  random_150: {
    id: "random_150",
    name: "Random Dungeon 150",
    location: "random_pool",
    length: "long",

    monsterPool: "floor_scaled",
    bossPool: "floor_scaled",

    grid: [
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "##########",
      "####E#####",
      "####R#####",
      "####M#####",
      "##MRM#####",
      "####MMRRRC",
      "CRRRR#####",
      "####R#####",
      "####RRRR##",
      "#######B##",
      "#######S##",
      "##########",
      "##########"
    ]
  }
};

// Browser/global compatibility
if (typeof window !== "undefined") {
  window.MAPS = MAPS;
}

// CommonJS compatibility
if (typeof module !== "undefined") {
  module.exports = MAPS;
}
