// =========================
// SKILLS.JS
// Obtainable skill definitions. Not character-specific yet.
// =========================

(function (global) {
  const SKILL_DATA = {
  "blade_rush": {
    "id": "blade_rush",
    "name": "Blade Rush",
    "type": "monster",
    "category": "physical",
    "levelReq": 1,
    "mpCost": 10,
    "shop": "starter",
    "ownedDefault": true,
    "price": 0,
    "baseMultiplier": 1.55,
    "ultimateMultiplier": 3.25,
    "piercePct": 20,
    "ultimatePiercePct": 55,
    "description": "Fast physical attack with moderate pierce."
  },
  "armor_break": {
    "id": "armor_break",
    "name": "Armor Break",
    "type": "monster",
    "category": "physical",
    "levelReq": 1,
    "mpCost": 8,
    "shop": "starter",
    "ownedDefault": true,
    "price": 0,
    "baseMultiplier": 1.25,
    "ultimateMultiplier": 2.35,
    "piercePct": 45,
    "ultimatePiercePct": 80,
    "description": "Physical attack that cuts through enemy defense."
  },
  "vampiric_slash": {
    "id": "vampiric_slash",
    "name": "Vampiric Slash",
    "type": "monster",
    "category": "physical",
    "levelReq": 1,
    "mpCost": 12,
    "shop": "starter",
    "ownedDefault": true,
    "price": 0,
    "baseMultiplier": 1.15,
    "ultimateMultiplier": 2.25,
    "piercePct": 10,
    "ultimatePiercePct": 30,
    "lifeStealPct": 35,
    "ultimateLifeStealPct": 75,
    "description": "Deals damage and steals health."
  },
  "heal_1": {
    "id": "heal_1",
    "name": "Heal I",
    "type": "self",
    "category": "support",
    "effect": "heal",
    "levelReq": 2,
    "mpCost": 8,
    "shop": "basic",
    "price": 120,
    "power": 35,
    "ultimatePower": 95,
    "description": "Restore a small amount of HP."
  },
  "heal_2": {
    "id": "heal_2",
    "name": "Heal II",
    "type": "self",
    "category": "support",
    "effect": "heal",
    "levelReq": 6,
    "mpCost": 16,
    "shop": "basic",
    "price": 360,
    "power": 80,
    "ultimatePower": 190,
    "description": "Restore a moderate amount of HP."
  },
  "heal_3": {
    "id": "heal_3",
    "name": "Heal III",
    "type": "self",
    "category": "support",
    "effect": "heal",
    "levelReq": 12,
    "mpCost": 28,
    "shop": "secret",
    "secret": true,
    "price": 900,
    "power": 165,
    "ultimatePower": 360,
    "description": "Restore a large amount of HP."
  },
  "haste": {
    "id": "haste",
    "name": "Haste",
    "type": "self",
    "category": "support",
    "effect": "haste",
    "levelReq": 4,
    "mpCost": 14,
    "shop": "basic",
    "price": 260,
    "power": 35,
    "ultimatePower": 65,
    "dodgePct": 10,
    "durationTicks": 26,
    "ultimateDurationTicks": 42,
    "description": "Temporarily increases speed and dodge potential."
  },
  "iron_skin": {
    "id": "iron_skin",
    "name": "Iron Skin",
    "type": "self",
    "category": "support",
    "effect": "iron_skin",
    "levelReq": 4,
    "mpCost": 12,
    "shop": "basic",
    "price": 240,
    "power": 35,
    "ultimatePower": 70,
    "durationTicks": 28,
    "ultimateDurationTicks": 44,
    "description": "Temporarily increases physical defense."
  },
  "mana_regen": {
    "id": "mana_regen",
    "name": "Mana Regen",
    "type": "self",
    "category": "support",
    "effect": "mana_regen",
    "levelReq": 7,
    "mpCost": 10,
    "shop": "secret",
    "secret": true,
    "price": 520,
    "power": 2,
    "ultimatePower": 4,
    "durationTicks": 28,
    "ultimateDurationTicks": 46,
    "description": "Restores MP over a short period."
  },
  "fire_weapon": {
    "id": "fire_weapon",
    "name": "Fire Weapon",
    "type": "self",
    "category": "enchant",
    "effect": "weapon_enchant",
    "element": "fire",
    "levelReq": 5,
    "mpCost": 14,
    "shop": "basic",
    "secret": false,
    "price": 280,
    "power": 25,
    "ultimatePower": 50,
    "durationTicks": 30,
    "ultimateDurationTicks": 50,
    "description": "Adds fire damage to weapon attacks."
  },
  "ice_weapon": {
    "id": "ice_weapon",
    "name": "Ice Weapon",
    "type": "self",
    "category": "enchant",
    "effect": "weapon_enchant",
    "element": "ice",
    "levelReq": 5,
    "mpCost": 14,
    "shop": "basic",
    "secret": false,
    "price": 280,
    "power": 25,
    "ultimatePower": 50,
    "durationTicks": 30,
    "ultimateDurationTicks": 50,
    "description": "Adds ice damage to weapon attacks."
  },
  "shock_weapon": {
    "id": "shock_weapon",
    "name": "Shock Weapon",
    "type": "self",
    "category": "enchant",
    "effect": "weapon_enchant",
    "element": "shock",
    "levelReq": 5,
    "mpCost": 14,
    "shop": "basic",
    "secret": false,
    "price": 280,
    "power": 25,
    "ultimatePower": 50,
    "durationTicks": 30,
    "ultimateDurationTicks": 50,
    "description": "Adds shock damage to weapon attacks."
  },
  "holy_weapon": {
    "id": "holy_weapon",
    "name": "Holy Weapon",
    "type": "self",
    "category": "enchant",
    "effect": "weapon_enchant",
    "element": "holy",
    "levelReq": 9,
    "mpCost": 20,
    "shop": "secret",
    "secret": true,
    "price": 650,
    "power": 35,
    "ultimatePower": 70,
    "durationTicks": 30,
    "ultimateDurationTicks": 50,
    "description": "Adds holy damage to weapon attacks."
  },
  "dark_weapon": {
    "id": "dark_weapon",
    "name": "Dark Weapon",
    "type": "self",
    "category": "enchant",
    "effect": "weapon_enchant",
    "element": "dark",
    "levelReq": 9,
    "mpCost": 20,
    "shop": "secret",
    "secret": true,
    "price": 650,
    "power": 35,
    "ultimatePower": 70,
    "durationTicks": 30,
    "ultimateDurationTicks": 50,
    "description": "Adds dark damage to weapon attacks."
  },
  "double_slash": {
    "id": "double_slash",
    "name": "Double Slash",
    "type": "monster",
    "category": "physical",
    "levelReq": 3,
    "mpCost": 9,
    "shop": "basic",
    "price": 180,
    "hits": 2,
    "ultimateHits": 4,
    "baseMultiplier": 0.78,
    "ultimateMultiplier": 0.9,
    "piercePct": 5,
    "ultimatePiercePct": 15,
    "description": "Two quick physical hits."
  },
  "triple_slash": {
    "id": "triple_slash",
    "name": "Triple Slash",
    "type": "monster",
    "category": "physical",
    "levelReq": 8,
    "mpCost": 18,
    "shop": "secret",
    "secret": true,
    "price": 620,
    "hits": 3,
    "ultimateHits": 6,
    "baseMultiplier": 0.7,
    "ultimateMultiplier": 0.82,
    "piercePct": 10,
    "ultimatePiercePct": 25,
    "description": "Three fast physical hits."
  },
  "fire_strike_1": {
    "id": "fire_strike_1",
    "name": "Fire Strike 1",
    "type": "monster",
    "category": "fire",
    "element": "fire",
    "levelReq": 3,
    "mpCost": 10,
    "shop": "basic",
    "secret": false,
    "price": 200,
    "baseMultiplier": 1.15,
    "ultimateMultiplier": 2.15,
    "elementPct": 25,
    "description": "A weapon strike with fire damage."
  },
  "fire_strike_2": {
    "id": "fire_strike_2",
    "name": "Fire Strike 2",
    "type": "monster",
    "category": "fire",
    "element": "fire",
    "levelReq": 7,
    "mpCost": 18,
    "shop": "basic",
    "secret": false,
    "price": 440,
    "baseMultiplier": 1.35,
    "ultimateMultiplier": 2.65,
    "elementPct": 40,
    "description": "A weapon strike with fire damage."
  },
  "fire_strike_3": {
    "id": "fire_strike_3",
    "name": "Fire Strike 3",
    "type": "monster",
    "category": "fire",
    "element": "fire",
    "levelReq": 12,
    "mpCost": 30,
    "shop": "secret",
    "secret": true,
    "price": 900,
    "baseMultiplier": 1.65,
    "ultimateMultiplier": 3.25,
    "elementPct": 65,
    "description": "A weapon strike with fire damage."
  },
  "ice_strike_1": {
    "id": "ice_strike_1",
    "name": "Ice Strike 1",
    "type": "monster",
    "category": "ice",
    "element": "ice",
    "levelReq": 3,
    "mpCost": 10,
    "shop": "basic",
    "secret": false,
    "price": 200,
    "baseMultiplier": 1.15,
    "ultimateMultiplier": 2.15,
    "elementPct": 25,
    "description": "A weapon strike with ice damage."
  },
  "ice_strike_2": {
    "id": "ice_strike_2",
    "name": "Ice Strike 2",
    "type": "monster",
    "category": "ice",
    "element": "ice",
    "levelReq": 7,
    "mpCost": 18,
    "shop": "basic",
    "secret": false,
    "price": 440,
    "baseMultiplier": 1.35,
    "ultimateMultiplier": 2.65,
    "elementPct": 40,
    "description": "A weapon strike with ice damage."
  },
  "ice_strike_3": {
    "id": "ice_strike_3",
    "name": "Ice Strike 3",
    "type": "monster",
    "category": "ice",
    "element": "ice",
    "levelReq": 12,
    "mpCost": 30,
    "shop": "secret",
    "secret": true,
    "price": 900,
    "baseMultiplier": 1.65,
    "ultimateMultiplier": 3.25,
    "elementPct": 65,
    "description": "A weapon strike with ice damage."
  },
  "shock_strike_1": {
    "id": "shock_strike_1",
    "name": "Shock Strike 1",
    "type": "monster",
    "category": "shock",
    "element": "shock",
    "levelReq": 3,
    "mpCost": 10,
    "shop": "basic",
    "secret": false,
    "price": 200,
    "baseMultiplier": 1.15,
    "ultimateMultiplier": 2.15,
    "elementPct": 25,
    "description": "A weapon strike with shock damage."
  },
  "shock_strike_2": {
    "id": "shock_strike_2",
    "name": "Shock Strike 2",
    "type": "monster",
    "category": "shock",
    "element": "shock",
    "levelReq": 7,
    "mpCost": 18,
    "shop": "basic",
    "secret": false,
    "price": 440,
    "baseMultiplier": 1.35,
    "ultimateMultiplier": 2.65,
    "elementPct": 40,
    "description": "A weapon strike with shock damage."
  },
  "shock_strike_3": {
    "id": "shock_strike_3",
    "name": "Shock Strike 3",
    "type": "monster",
    "category": "shock",
    "element": "shock",
    "levelReq": 12,
    "mpCost": 30,
    "shop": "secret",
    "secret": true,
    "price": 900,
    "baseMultiplier": 1.65,
    "ultimateMultiplier": 3.25,
    "elementPct": 65,
    "description": "A weapon strike with shock damage."
  },
  "holy_strike_1": {
    "id": "holy_strike_1",
    "name": "Holy Strike 1",
    "type": "monster",
    "category": "holy",
    "element": "holy",
    "levelReq": 6,
    "mpCost": 16,
    "shop": "basic",
    "secret": false,
    "price": 380,
    "baseMultiplier": 1.15,
    "ultimateMultiplier": 2.15,
    "elementPct": 25,
    "description": "A weapon strike with holy damage."
  },
  "holy_strike_2": {
    "id": "holy_strike_2",
    "name": "Holy Strike 2",
    "type": "monster",
    "category": "holy",
    "element": "holy",
    "levelReq": 10,
    "mpCost": 24,
    "shop": "secret",
    "secret": true,
    "price": 620,
    "baseMultiplier": 1.35,
    "ultimateMultiplier": 2.65,
    "elementPct": 40,
    "description": "A weapon strike with holy damage."
  },
  "holy_strike_3": {
    "id": "holy_strike_3",
    "name": "Holy Strike 3",
    "type": "monster",
    "category": "holy",
    "element": "holy",
    "levelReq": 15,
    "mpCost": 36,
    "shop": "secret",
    "secret": true,
    "price": 1080,
    "baseMultiplier": 1.65,
    "ultimateMultiplier": 3.25,
    "elementPct": 65,
    "description": "A weapon strike with holy damage."
  },
  "dark_strike_1": {
    "id": "dark_strike_1",
    "name": "Dark Strike 1",
    "type": "monster",
    "category": "dark",
    "element": "dark",
    "levelReq": 6,
    "mpCost": 16,
    "shop": "basic",
    "secret": false,
    "price": 380,
    "baseMultiplier": 1.15,
    "ultimateMultiplier": 2.15,
    "elementPct": 25,
    "description": "A weapon strike with dark damage."
  },
  "dark_strike_2": {
    "id": "dark_strike_2",
    "name": "Dark Strike 2",
    "type": "monster",
    "category": "dark",
    "element": "dark",
    "levelReq": 10,
    "mpCost": 24,
    "shop": "secret",
    "secret": true,
    "price": 620,
    "baseMultiplier": 1.35,
    "ultimateMultiplier": 2.65,
    "elementPct": 40,
    "description": "A weapon strike with dark damage."
  },
  "dark_strike_3": {
    "id": "dark_strike_3",
    "name": "Dark Strike 3",
    "type": "monster",
    "category": "dark",
    "element": "dark",
    "levelReq": 15,
    "mpCost": 36,
    "shop": "secret",
    "secret": true,
    "price": 1080,
    "baseMultiplier": 1.65,
    "ultimateMultiplier": 3.25,
    "elementPct": 65,
    "description": "A weapon strike with dark damage."
  }
};

  global.SKILL_DATA = SKILL_DATA;
})(typeof window !== "undefined" ? window : globalThis);
